services:
    # factory
    AnyKey\MobilePaymentsBundle\Factory\ProviderFactory:
        arguments:
            - !tagged mobile_payment.provider
    # providers
    AnyKey\MobilePaymentsBundle\Providers\Amazon: ~
    AnyKey\MobilePaymentsBundle\Providers\Apple: ~
    AnyKey\MobilePaymentsBundle\Providers\Google: ~
    AnyKey\MobilePaymentsBundle\Providers\Windows:
        autowire: true
