services:
    # factory
    AnyKey\Factory\ProviderFactory:
        arguments:
            - !tagged mobile_payment.provider
    # providers
    AnyKey\Providers\Amazon: ~
    AnyKey\Providers\Apple: ~
    AnyKey\Providers\Google: ~
    AnyKey\Providers\Windows: ~
